# Generated by Django 6.0 on 2025-12-16 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HS", "高校生"),
                            ("UNIV", "大学生"),
                            ("IND", "独立・社会人"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("P", "投手"),
                            ("C", "捕手"),
                            ("IF", "内野手"),
                            ("OF", "外野手"),
                        ],
                        max_length=5,
                    ),
                ),
                ("team", models.CharField(max_length=100)),
                (
                    "bats_throws",
                    models.CharField(
                        choices=[
                            ("RR", "右投右打"),
                            ("RL", "右投左打"),
                            ("RB", "右投両打"),
                            ("LR", "左投右打"),
                            ("LL", "左投左打"),
                            ("LB", "左投両打"),
                        ],
                        max_length=10,
                    ),
                ),
                ("height", models.IntegerField()),
                ("weight", models.IntegerField()),
                ("video_url", models.URLField(blank=True)),
                ("scout_comment", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="draft.player",
                    ),
                ),
            ],
        ),
    ]
