# Generated by Django 6.0 on 2025-12-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="introduction",
            field=models.TextField(blank=True, verbose_name="選手紹介"),
        ),
        migrations.AlterField(
            model_name="player",
            name="bats_throws",
            field=models.CharField(
                choices=[
                    ("R/R", "右投右打"),
                    ("R/L", "右投左打"),
                    ("R/B", "右投両打"),
                    ("L/R", "左投右打"),
                    ("L/L", "左投左打"),
                    ("L/B", "左投両打"),
                ],
                max_length=10,
            ),
        ),
    ]
