# Generated by Django 6.0 on 2026-01-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0002_player_introduction_alter_player_bats_throws"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "order_2025",
                    models.IntegerField(help_text="2025年順位（1が最下位）"),
                ),
            ],
        ),
    ]
