# Generated by Django 6.0 on 2026-01-13 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0003_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="drafted_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="draft.team",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="is_drafted",
            field=models.BooleanField(default=False),
        ),
    ]
