# Generated by Django 6.0 on 2026-01-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0004_player_drafted_team_player_is_drafted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="order_2025",
            new_name="draft_order",
        ),
    ]
