# Generated by Django 6.0 on 2026-01-16 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0005_rename_order_2025_team_draft_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round", models.IntegerField(default=1)),
                ("is_finished", models.BooleanField(default=False)),
                (
                    "current_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="draft.team",
                    ),
                ),
            ],
        ),
    ]
