# Generated by Django 6.0 on 2026-01-23 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0006_draftstate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="is_drafted",
        ),
        migrations.RemoveField(
            model_name="team",
            name="draft_order",
        ),
        migrations.AddField(
            model_name="team",
            name="order",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Pick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="draft.player"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="draft.team"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DraftState",
        ),
    ]
