# Generated by Django 6.0.1 on 2026-01-27 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0007_remove_player_is_drafted_remove_team_draft_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="video_url",
        ),
    ]
