# Generated by Django 6.0.1 on 2026-01-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0008_remove_player_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="rank",
            field=models.CharField(
                choices=[
                    ("S", "1位指名候補"),
                    ("A", "上位指名候補"),
                    ("B", "中位指名候補"),
                    ("C", "下位指名候補"),
                    ("D", "育成指名候補"),
                ],
                default=3,
            ),
        ),
    ]
