# Generated by Django 6.0.1 on 2026-01-30 03:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0009_comment_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="batcontroll",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="breakingball",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="command",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="defense",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="mechanics",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="potential",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="power",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="speed",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="velocity",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="rank",
            field=models.CharField(
                choices=[
                    ("S", "1位指名候補"),
                    ("A", "上位指名候補"),
                    ("B", "中位指名候補"),
                    ("C", "下位指名候補"),
                    ("D", "育成指名候補"),
                ],
                max_length=1,
            ),
        ),
    ]
