# Generated by Django 6.0.1 on 2026-01-30 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0010_comment_batcontroll_comment_breakingball_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="batcontroll",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=2,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="ミート",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="breakingball",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=2,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="変化球",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="command",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=2,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="コントロール",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="defense",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=2,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="守備",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="mechanics",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=2,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="フォーム",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="potential",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=2,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="将来性",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="power",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=2,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="パワー",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="rank",
            field=models.CharField(
                choices=[
                    ("S", "S:1位指名候補"),
                    ("A", "A:上位指名候補"),
                    ("B", "B:中位指名候補"),
                    ("C", "C:下位指名候補"),
                    ("D", "D:育成指名候補"),
                ],
                max_length=1,
                verbose_name="評価",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="speed",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=2,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="走塁",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(verbose_name="コメント"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="velocity",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=2,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="球威",
            ),
        ),
    ]
