# Generated by Django 6.0.1 on 2026-02-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0011_alter_comment_batcontroll_alter_comment_breakingball_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="primary_color",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
    ]
