# Generated by Django 6.0.1 on 2026-02-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0012_team_primary_color"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="primary_color",
            new_name="first_color",
        ),
        migrations.AddField(
            model_name="team",
            name="second_color",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
    ]
